[package]
name = "game-rs"
version = "0.1.0"
authors = ["damnever <dxc.wolf@gmail.com>"]

[dependencies]
termion = "1.0"
rand = "0.3.15"

[[bin]]
name = "2048"
path = "src/2048/main.rs"

[[bin]]
name = "snake"
path = "src/snake/main.rs"
